version: '3.3'
networks:
  nginx:
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 5000:5000 # container registry
      - 80:80 # kubernetes - hello world
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/index.html:/usr/share/nginx/html/index.html
    networks:
      - nginx

  registry:
    image: registry:2
    restart: unless-stopped
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - /mnt/registry:/var/lib/registry
    networks:
      - nginx
