apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx

